#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 14 18:15:25 2018

@author: samiksadhu
"""

'Gather all data together into one'

import sys 
import argparse
sys.path.append('../../tools')
from trainMLPClassifier import tidyData
import numpy as np
from os.path import join

parser=argparse.ArgumentParser('Gather all data generated by feature generation module')
parser.add_argument('data_directory',help='Location of all the data')
args=parser.parse_args()

print('%s:Gathering up data all data ...' % sys.argv[0])
train_data, train_labels, test_data, test_labels=tidyData(args.data_directory)

np.save(join(args.data_directory,'train_data.npy'),train_data)
np.save(join(args.data_directory,'train_labels.npy'),train_labels)
np.save(join(args.data_directory,'test_data.npy'),test_data)
np.save(join(args.data_directory,'test_labels.npy'),test_labels)